## -*- encoding: utf-8 -*-
## This file (t01-sequences.sagetex.sage) was *autogenerated* from t01-sequences.tex with sagetex.sty version 2019/01/09 v3.3.
import sagetex
_st_ = sagetex.SageTeXProcessor('t01-sequences', version='2019/01/09 v3.3', version_check=True)
_st_.current_tex_line = 23
_st_.blockbegin()
try:
 var('n');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(26)
_st_.blockend()
try:
 _st_.current_tex_line = 28
 _st_.inline(0, latex([a(i) for i in (0..4)]))
except:
 _st_.goboom(28)
_st_.current_tex_line = 31
_st_.blockbegin()
try:
 var('n');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(34)
_st_.blockend()
try:
 _st_.current_tex_line = 37
 _st_.inline(1, latex([a(i) for i in (1..5)]))
except:
 _st_.goboom(37)
_st_.current_tex_line = 40
_st_.blockbegin()
try:
 var('n');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(43)
_st_.blockend()
try:
 _st_.current_tex_line = 46
 _st_.inline(2, latex([a(i) for i in (1..5)]))
except:
 _st_.goboom(46)
_st_.current_tex_line = 49
_st_.blockbegin()
try:
 var('n');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(52)
_st_.blockend()
try:
 _st_.current_tex_line = 55
 _st_.inline(3, latex([a(i) for i in (1..5)]))
except:
 _st_.goboom(55)
_st_.current_tex_line = 58
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0 or n==1:
         return 1
     else:
         return a(n-1) + a(n-2);
except:
 _st_.goboom(65)
_st_.blockend()
try:
 _st_.current_tex_line = 68
 _st_.inline(4, latex([a(i) for i in (0..4)]))
except:
 _st_.goboom(68)
_st_.current_tex_line = 71
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==1:
         return 3
     else:
         return a(n-1)/(n-1);
except:
 _st_.goboom(78)
_st_.blockend()
try:
 _st_.current_tex_line = 81
 _st_.inline(5, latex([a(i) for i in (1..5)]))
except:
 _st_.goboom(81)
_st_.current_tex_line = 84
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0:
         return 2
     else:
         return a(n-1)/(1+a(n-1));
except:
 _st_.goboom(91)
_st_.blockend()
try:
 _st_.current_tex_line = 94
 _st_.inline(6, latex([a(i) for i in (0..4)]))
except:
 _st_.goboom(94)
_st_.current_tex_line = 97
_st_.blockbegin()
try:
 var('n');
 def a(n):
     return 3^n/factorial(2*n)
except:
 _st_.goboom(101)
_st_.blockend()
try:
 _st_.current_tex_line = 104
 _st_.inline(7, latex([a(i) for i in (0..4)]))
except:
 _st_.goboom(104)
_st_.current_tex_line = 108
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(111)
_st_.blockend()
try:
 _st_.current_tex_line = 114
 _st_.inline(8, latex(a(2*m+3)))
except:
 _st_.goboom(114)
_st_.current_tex_line = 115
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(118)
_st_.blockend()
try:
 _st_.current_tex_line = 121
 _st_.inline(9, latex(a(2*m+3)))
except:
 _st_.goboom(121)
_st_.current_tex_line = 122
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(125)
_st_.blockend()
try:
 _st_.current_tex_line = 128
 _st_.inline(10, latex(a(2*m+3)))
except:
 _st_.goboom(128)
_st_.current_tex_line = 129
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(132)
_st_.blockend()
try:
 _st_.current_tex_line = 135
 _st_.inline(11, latex(a(2*m+3)))
except:
 _st_.goboom(135)
_st_.current_tex_line = 136
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(139)
_st_.blockend()
_st_.current_tex_line = 164
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(167)
_st_.blockend()
try:
 _st_.current_tex_line = 170
 _st_.plot(0, format='notprovided', _p_=list_plot([a(i) for i in (0..50)]))
except:
 _st_.goboom(170)
_st_.current_tex_line = 171
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(174)
_st_.blockend()
try:
 _st_.current_tex_line = 177
 _st_.plot(1, format='notprovided', _p_=list_plot([a(i) for i in (1..50)]))
except:
 _st_.goboom(177)
_st_.current_tex_line = 178
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(181)
_st_.blockend()
try:
 _st_.current_tex_line = 184
 _st_.plot(2, format='notprovided', _p_=list_plot([a(i) for i in (1..50)]))
except:
 _st_.goboom(184)
_st_.current_tex_line = 185
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(188)
_st_.blockend()
try:
 _st_.current_tex_line = 191
 _st_.plot(3, format='notprovided', _p_=list_plot([a(i) for i in (1..50)]))
except:
 _st_.goboom(191)
_st_.current_tex_line = 192
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0 or n==1:
         return 1
     else:
         return a(n-1) + a(n-2);
except:
 _st_.goboom(199)
_st_.blockend()
try:
 _st_.current_tex_line = 203
 _st_.plot(4, format='notprovided', _p_=list_plot([a(i) for i in (0..10)]))
except:
 _st_.goboom(203)
_st_.current_tex_line = 204
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==1:
         return 3
     else:
         return a(n-1)/(n-1);
except:
 _st_.goboom(211)
_st_.blockend()
try:
 _st_.current_tex_line = 214
 _st_.plot(5, format='notprovided', _p_=list_plot([a(i) for i in (1..15)]))
except:
 _st_.goboom(214)
_st_.current_tex_line = 215
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0:
         return 2
     else:
         return a(n-1)/(1+a(n-1));
except:
 _st_.goboom(222)
_st_.blockend()
try:
 _st_.current_tex_line = 225
 _st_.plot(6, format='notprovided', _p_=list_plot([a(i) for i in (1..10)]))
except:
 _st_.goboom(225)
_st_.current_tex_line = 226
_st_.blockbegin()
try:
 var('n');
 def a(n):
     return 3^n/factorial(2*n)
except:
 _st_.goboom(230)
_st_.blockend()
try:
 _st_.current_tex_line = 233
 _st_.plot(7, format='notprovided', _p_=list_plot([a(i) for i in (1..8)]))
except:
 _st_.goboom(233)
_st_.endofdoc()
