## -*- encoding: utf-8 -*-
## This file (t03-functions.sagetex.sage) was *autogenerated* from t03-functions.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('t03-functions', version='2015/08/26 v3.0-92d9f7a', version_check=True)
try:
 _st_.current_tex_line = 92
 _st_.plot(0, format='notprovided', _p_=plot((x^2+1)/(2*x - 3), (x,-5,1.4), color='black'))
except:
 _st_.goboom(92)
try:
 _st_.current_tex_line = 92
 _st_.plot(1, format='notprovided', _p_=plot((x^2+1)/(2*x - 3), (x,1.6,5), color='black'))
except:
 _st_.goboom(92)
try:
 _st_.current_tex_line = 92
 _st_.plot(2, format='notprovided', _p_=plot(x^2 - 3*x -1, (x,-5,5), color='black'))
except:
 _st_.goboom(92)
try:
 _st_.current_tex_line = 121
 _st_.plot(3, format='notprovided', _p_=plot(tan(x), (x,-pi/2+0.1,pi/2 - 0.1), color='black', ticks=pi/4, tick_formatter=pi))
except:
 _st_.goboom(121)
_st_.current_tex_line = 177
_st_.blockbegin()
try:
 var('x')
 f(x) = -2*x-3
 g(x)=x^2+3*x+1
 h(x)=x/2
except:
 _st_.goboom(182)
_st_.blockend()
try:
 _st_.current_tex_line = 192
 _st_.inline(0, latex(f(g(h(x)))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(1, latex(expand(g(f(h(x))))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(2, latex(expand(h(g(f(x))))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(3, latex(expand(f(f(x)))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(4, latex(expand(g(g(x)))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(5, latex(expand(h(h(x)))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(0, latex(f(g(h(x)))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(1, latex(expand(g(f(h(x))))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(2, latex(expand(h(g(f(x))))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(3, latex(expand(f(f(x)))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(4, latex(expand(g(g(x)))))
except:
 _st_.goboom(192)
try:
 _st_.current_tex_line = 192
 _st_.inline(5, latex(expand(h(h(x)))))
except:
 _st_.goboom(192)
_st_.endofdoc()
