## -*- encoding: utf-8 -*-
## This file (tutorial-sheet-02-series.sagetex.sage) was *autogenerated* from tutorial-sheet-02-series.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('tutorial-sheet-02-series', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = 74
_st_.blockbegin()
try:
 var('n')
 a(n) = (-1)^n/(2*n - 1)
 b(n) = (n+1)/(n^3+2)
 c(n) = 3/(factorial(n))
 
 A=[a(i) for i in (1..6)]
 B=[b(i) for i in (1..6)]
 C=[c(i) for i in (1..6)]
 D=[sum(j^(-2) for j in range(1,n+1)) for n in (1..6)]
except:
 _st_.goboom(84)
_st_.blockend()
try:
 _st_.current_tex_line = 89
 _st_.inline(0, latex(D[0]))
except:
 _st_.goboom(89)
try:
 _st_.current_tex_line = 89
 _st_.inline(1, latex(D[1]))
except:
 _st_.goboom(89)
try:
 _st_.current_tex_line = 89
 _st_.inline(2, latex(D[2]))
except:
 _st_.goboom(89)
try:
 _st_.current_tex_line = 89
 _st_.inline(3, latex(D[3]))
except:
 _st_.goboom(89)
try:
 _st_.current_tex_line = 89
 _st_.inline(4, latex(D[4]))
except:
 _st_.goboom(89)
try:
 _st_.current_tex_line = 89
 _st_.inline(5, latex(D[5]))
except:
 _st_.goboom(89)
_st_.current_tex_line = 141
_st_.blockbegin()
try:
 var('n')
 a = sum(2/3 * (1/3)^(n+1),n,1,oo)
 b = sum(3 * (1/2)^(n),n,1,oo)
except:
 _st_.goboom(145)
_st_.blockend()
try:
 _st_.current_tex_line = 149
 _st_.inline(6, latex(a))
except:
 _st_.goboom(149)
try:
 _st_.current_tex_line = 149
 _st_.inline(7, latex(b))
except:
 _st_.goboom(149)
_st_.current_tex_line = 154
_st_.blockbegin()
try:
 var('n')
 a = sum(1234/(10000^n),n,1,oo)
except:
 _st_.goboom(157)
_st_.blockend()
try:
 _st_.current_tex_line = 163
 _st_.inline(8, latex(a))
except:
 _st_.goboom(163)
_st_.current_tex_line = 247
_st_.blockbegin()
try:
 var('n')
 a(n) = (9*n^2+33*n+12)/((n+4)*(n+3)*(n+1)*n)
 b(n) = 8/(n^2+6*n+5)
 c(n) = 9/(n^2+n - 2)
 d(n) = (11 - n)/(n^2+6*n+5)
except:
 _st_.goboom(253)
_st_.blockend()
try:
 _st_.current_tex_line = 262
 _st_.inline(9, latex(a(n).partial_fraction(n)))
except:
 _st_.goboom(262)
try:
 _st_.current_tex_line = 262
 _st_.inline(10, latex(sum(a(n),n,1,oo)))
except:
 _st_.goboom(262)
try:
 _st_.current_tex_line = 269
 _st_.inline(11, latex(b(n).partial_fraction(n)))
except:
 _st_.goboom(269)
try:
 _st_.current_tex_line = 269
 _st_.inline(12, latex(sum(b(n),n,1,oo)))
except:
 _st_.goboom(269)
try:
 _st_.current_tex_line = 276
 _st_.inline(13, latex(c(n).partial_fraction(n)))
except:
 _st_.goboom(276)
try:
 _st_.current_tex_line = 276
 _st_.inline(14, latex(sum(c(n),n,2,oo)))
except:
 _st_.goboom(276)
try:
 _st_.current_tex_line = 286
 _st_.inline(15, latex(d(n).partial_fraction(n)))
except:
 _st_.goboom(286)
_st_.endofdoc()
