## -*- encoding: utf-8 -*-
## This file (tutorial-sheet-04-differential-calculus.sagetex.sage) was *autogenerated* from tutorial-sheet-04-differential-calculus.tex with sagetex.sty version 2019/01/09 v3.3.
import sagetex
_st_ = sagetex.SageTeXProcessor('tutorial-sheet-04-differential-calculus', version='2019/01/09 v3.3', version_check=True)
_st_.current_tex_line = 182
_st_.blockbegin()
try:
 var('t,x,y,z')
 fa=x^5 + 3*x^4 - 5*x^2 + 10
 fb=3*x^(1/2) - x^(3/2) + 2*x^(-1/2)
 fc=sqrt(3*t)+3*sqrt(t)
 fd=(2 + 5*y + 1/2 *y^2)^(1/2)
 fe=(z+1)*sqrt(z^4 - 2*z +2)
 ff=x / sqrt(1 - 4*x^2)
 fg = sqrt(1 + sqrt(x))
except:
 _st_.goboom(191)
_st_.blockend()
try:
 _st_.current_tex_line = 210
 _st_.inline(0, latex(diff(fa,x)(x)))
except:
 _st_.goboom(210)
try:
 _st_.current_tex_line = 210
 _st_.inline(1, latex(diff(fb,x)(x)))
except:
 _st_.goboom(210)
try:
 _st_.current_tex_line = 210
 _st_.inline(2, latex(diff(fc,t)(t)))
except:
 _st_.goboom(210)
try:
 _st_.current_tex_line = 210
 _st_.inline(3, latex(diff(fd,y)(y)))
except:
 _st_.goboom(210)
try:
 _st_.current_tex_line = 210
 _st_.inline(4, latex(diff(fe,z)(z)))
except:
 _st_.goboom(210)
try:
 _st_.current_tex_line = 210
 _st_.inline(5, latex(diff(ff,x)(x)))
except:
 _st_.goboom(210)
try:
 _st_.current_tex_line = 210
 _st_.inline(6, latex(diff(fg,x)(x)))
except:
 _st_.goboom(210)
_st_.endofdoc()
